#+title: orderless-extras: Extensions for orderless
#+author: Pablo Stafforini
#+email: pablo@stafforini.com
#+language: en
#+options: ':t toc:t author:t email:t num:t
#+startup: content
#+export_file_name: orderless-extras.info
#+texinfo_filename: orderless-extras.info
#+texinfo_dir_category: Emacs misc features
#+texinfo_dir_title: Orderless Extras: (orderless-extras)
#+texinfo_dir_desc: Extensions for orderless

This manual describes the features and customization options for the Emacs Lisp file =orderless-extras.el=.

* Overview
:PROPERTIES:
:CUSTOM_ID: h:overview
:END:

=orderless-extras.el= extends =orderless=, the completion style that matches candidates against space-separated components in any order. While =orderless= ships with several matching styles (literal, regexp, flex, initialism, and others), activating a particular style for a single component within a query requires a dispatcher function.

This package provides four dispatchers, each triggered by appending a suffix character to a search component:

| Suffix | Style                          | Section                                 |
|--------+--------------------------------+-----------------------------------------|
| =~=    | ~orderless-flex~               | [[#h:flex-dispatcher][Flex matching]]   |
| =,=    | ~orderless-initialism~         | [[#h:initialism-dispatcher][Initialism]] |
| =;=    | ~orderless-prefixes~           | [[#h:prefixes-dispatcher][Prefixes]]     |
| =!=    | ~orderless-without-literal~    | [[#h:exclusion-dispatcher][Exclusion]]    |

To use these dispatchers, add them to the ~orderless-style-dispatchers~ list:

#+begin_src emacs-lisp
(setq orderless-style-dispatchers
      '(orderless-extras-flex-dispatcher
        orderless-extras-initialism-dispatcher
        orderless-extras-prefixes-dispatcher
        orderless-extras-exclusion-dispatcher))
#+end_src

* Functions
:PROPERTIES:
:CUSTOM_ID: h:functions
:END:

** Flex matching
:PROPERTIES:
:CUSTOM_ID: h:flex-dispatcher
:END:

#+findex: orderless-extras-flex-dispatcher
The function ~orderless-extras-flex-dispatcher~ activates ~orderless-flex~ matching for any component that ends with a tilde (=~=). Flex matching allows characters to appear in order but not necessarily adjacent, which is useful when you remember the overall shape of a name but not its exact spelling.

For example, in the query =file sme~ na=, the component =sme~= would flexibly match candidates containing =s=, =m=, and =e= in that order (such as "some"), while =file= and =na= would use the default matching style.

** Initialism
:PROPERTIES:
:CUSTOM_ID: h:initialism-dispatcher
:END:

#+findex: orderless-extras-initialism-dispatcher
The function ~orderless-extras-initialism-dispatcher~ activates ~orderless-initialism~ matching for any component that ends with a comma (=,=). Initialism matching treats each character in the component as the first letter of a word, which is particularly effective for long hyphenated Emacs symbol names.

For example, =ffap,= would match ~find-file-at-point~ because =f=, =f=, =a=, and =p= are the initials of each word.

** Prefixes
:PROPERTIES:
:CUSTOM_ID: h:prefixes-dispatcher
:END:

#+findex: orderless-extras-prefixes-dispatcher
The function ~orderless-extras-prefixes-dispatcher~ activates ~orderless-prefixes~ matching for any component that ends with a semicolon (=;=). Prefix matching requires each character group (separated by word boundaries) in the component to appear at the beginning of corresponding words in the candidate.

For example, =or-ex;= would match =orderless-extras= because =or= is a prefix of =orderless= and =ex= is a prefix of =extras=. It would not match a candidate where =ex= appeared in the middle of a word.

** Exclusion
:PROPERTIES:
:CUSTOM_ID: h:exclusion-dispatcher
:END:

#+findex: orderless-extras-exclusion-dispatcher
The function ~orderless-extras-exclusion-dispatcher~ activates ~orderless-without-literal~ matching for any component that ends with an exclamation mark (=!=). This excludes any candidate that contains the literal text of the component (minus the trailing =!=).

For example, the query =file tmp!= would match candidates containing =file= but exclude any that also contain =tmp=. This is useful for filtering out noise from a broad search.

* Indices
:PROPERTIES:
:CUSTOM_ID: h:indices
:END:

** Function index
:PROPERTIES:
:INDEX: fn
:CUSTOM_ID: h:function-index
:END:

** Variable index
:PROPERTIES:
:INDEX: vr
:CUSTOM_ID: h:variable-index
:END:
