#!/usr/bin/env bash
# Shared JSON helpers for Codex hook payloads.

CODEX_HOOK_JQ_DEFS='
  def codex_tool_input:
    .tool_input? as $input |
    if ($input | type) == "object" then $input
    elif ($input | type) == "string" then
      ($input as $raw |
       (try ($raw | fromjson) catch {"command": $raw}) |
       if type == "object" then . else {"command": $raw} end)
    else {}
    end;

  def codex_tool_response:
    .tool_response? as $response |
    if ($response | type) == "object" then $response
    elif ($response | type) == "string" then
      ($response as $raw |
       (try ($raw | fromjson) catch {"output": $raw}) |
       if type == "object" then . else {"output": $raw} end)
    else {}
    end;
'

codex_hook_jq() {
  local input="$1"
  local filter="$2"
  printf '%s' "$input" | jq -r "${CODEX_HOOK_JQ_DEFS}
${filter}"
}

codex_tool_name() {
  local input="$1"
  codex_hook_jq "$input" '.tool_name // empty'
}

codex_session_id() {
  local input="$1"
  codex_hook_jq "$input" '.session_id // empty'
}

codex_tool_input_field() {
  local input="$1"
  local field="$2"
  printf '%s' "$input" | jq -r --arg field "$field" "${CODEX_HOOK_JQ_DEFS}
codex_tool_input[\$field] // empty"
}

codex_shell_command() {
  local input="$1"
  codex_hook_jq "$input" '
    codex_tool_input.command //
    codex_tool_input.cmd //
    codex_tool_input.input //
    empty
  '
}

codex_shell_tool_p() {
  local tool_name="$1"
  case "$tool_name" in
    Bash|exec_command|functions.exec|functions.exec_command) return 0 ;;
    *) return 1 ;;
  esac
}

# Extract literal `cmd:` values from a functions.exec JavaScript program.
# Commands are NUL-delimited so embedded whitespace and newlines survive the
# trip back to Bash. This is intentionally a small lexer, not a JavaScript
# evaluator: nested exec_command calls generated by Codex use literal string
# values, and evaluating arbitrary hook input would itself be unsafe.
codex_nested_exec_commands() {
  python3 -c '
import sys

source = sys.stdin.read()
n = len(source)
i = 0


def skip_space(pos):
    while pos < n and source[pos].isspace():
        pos += 1
    return pos


def read_string(pos):
    quote = source[pos]
    pos += 1
    value = []
    escapes = {"n": "\n", "r": "\r", "t": "\t", "b": "\b", "f": "\f", "v": "\v"}
    while pos < n:
        char = source[pos]
        if char == quote:
            return "".join(value), pos + 1
        if char == "\\" and pos + 1 < n:
            escaped = source[pos + 1]
            if escaped == "x" and pos + 3 < n:
                try:
                    value.append(chr(int(source[pos + 2:pos + 4], 16)))
                    pos += 4
                    continue
                except ValueError:
                    pass
            if escaped == "u" and pos + 5 < n:
                try:
                    value.append(chr(int(source[pos + 2:pos + 6], 16)))
                    pos += 6
                    continue
                except ValueError:
                    pass
            if escaped == "\n":
                pos += 2
                continue
            value.append(escapes.get(escaped, escaped))
            pos += 2
            continue
        value.append(char)
        pos += 1
    return None, n


while i < n:
    start = i
    if source[i] in ("\"", chr(39)):
        key, after_key = read_string(i)
        if key != "cmd":
            i = after_key
            continue
        i = after_key
    elif source.startswith("cmd", i) and (i == 0 or not (source[i - 1].isalnum() or source[i - 1] in "_$")):
        after_key = i + 3
        if after_key < n and (source[after_key].isalnum() or source[after_key] in "_$"):
            i += 1
            continue
        i = after_key
    else:
        i += 1
        continue

    i = skip_space(i)
    if i >= n or source[i] != ":":
        i = start + 1
        continue
    i = skip_space(i + 1)
    if i >= n or source[i] not in ("\"", chr(39), "`"):
        i = start + 1
        continue
    command, i = read_string(i)
    if command is not None:
        sys.stdout.buffer.write(command.encode("utf-8") + b"\0")
'
}
